server {
    listen 8004;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "connect-src 'self' https://api.fiveline.store https://sonarcloud.io";

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
