server {
    listen 8004;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /sonar-api/ {
        proxy_pass https://sonarcloud.io/api/;
        proxy_ssl_server_name on;
    }

    location /api/health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
